//! Row decoders every family shares in the export direction: the md header,
//! localized strings, type descriptions, typed values, design-time and
//! metadata references, data paths, the attribute body with its choice
//! parameters and links, standard attributes. Each is the inverse of a load
//! direction encoder (`md_base`, `localized`, `types.rs`, `attribute.rs`, the
//! standard-attribute bag of `objects_parts.rs`) and writes XML elements.

use anyhow::{Result, anyhow, bail};

use super::super::brace::Brace;
use super::{
    Build, ExportContext, NameIndex, atom, el, is_nil, item, leaf, list, number, short, string,
    xml_text,
};
use crate::metadata_model::xml::Element;

/// The object a row belongs to: data paths and standard attributes are
/// spelled relative to it.
#[derive(Clone, Copy, Debug)]
pub(crate) struct Owner<'a> {
    pub kind: &'a str,
    /// `Catalog.X`
    pub full_name: &'a str,
}

/// `{3,{1,0,<uuid>},"Name",<synonym>,"Comment",0,0,<nil>,0}`.
pub(crate) struct Header {
    pub uuid: String,
    pub name: String,
    pub synonym: Brace,
    pub comment: String,
}

pub(crate) fn header(node: &Brace) -> Result<Header> {
    let items = list(node)?;
    if atom(item(items, 0)?)? != "3" || items.len() != 9 {
        bail!("not an md header: {}", short(node));
    }
    let identity = list(item(items, 1)?)?;
    Ok(Header {
        uuid: atom(item(identity, 2)?)?.to_string(),
        name: string(item(items, 2)?)?.to_string(),
        synonym: item(items, 3)?.clone(),
        comment: string(item(items, 4)?)?.to_string(),
    })
}

/// `Name`, `Synonym`, `Comment` of an md header (unprefixed, as every object
/// and child object writes them).
pub(crate) fn header_elements(header: &Header) -> Result<[Element; 3]> {
    Ok([
        leaf("Name", header.name.clone()),
        localized_element("Synonym", &header.synonym)?,
        leaf("Comment", xml_text(&header.comment)),
    ])
}

/// `{N,"lang","text",...}` -> `<qname><v8:item><v8:lang/><v8:content/></v8:item>...`.
pub(crate) fn localized_element(qname: &str, node: &Brace) -> Result<Element> {
    let items = list(node)?;
    let count = number(item(items, 0)?)? as usize;
    if items.len() != 1 + 2 * count {
        bail!("bad localized string {}", short(node));
    }
    let mut element = el(qname);
    for pair in items[1..].chunks(2) {
        element.children.push(
            el("v8:item")
                .child(leaf("v8:lang", string(&pair[0])?))
                .child(leaf("v8:content", xml_text(string(&pair[1])?))),
        );
    }
    Ok(element)
}

/// `0`/`1` -> `false`/`true`.
pub(crate) fn bool_text(node: &Brace) -> Result<&'static str> {
    match atom(node)? {
        "0" => Ok("false"),
        "1" => Ok("true"),
        other => bail!("expected 0/1, got {other}"),
    }
}

/// A stored code -> its XML spelling.
pub(crate) fn code_text(node: &Brace, table: &[(&'static str, i64)]) -> Result<&'static str> {
    let code = number(node)?;
    table
        .iter()
        .find_map(|(name, value)| (*value == code).then_some(*name))
        .ok_or_else(|| anyhow!("code {code} is not mapped"))
}

/// The full name of a referenced object; empty for the nil uuid.
pub(crate) fn reference_name(uuid: &str, names: &NameIndex) -> Result<String> {
    if is_nil(uuid) {
        return Ok(String::new());
    }
    names
        .name(uuid)
        .map(str::to_string)
        .ok_or_else(|| anyhow!("no name for uuid {uuid}"))
}

// ---------------------------------------------------------------------------
// Type descriptions.

/// Platform types a pattern names by uuid, with the text `<v8:Type>` writes.
/// A `d0p1:` prefix is generated by the writer from the element's depth.
const BUILTIN_TYPES: &[(&str, &str)] = &[
    ("e199ca70-93cf-46ce-a54b-6edc88c3a296", "v8:ValueStorage"),
    ("fc01b5df-97fe-449b-83d4-218a090e681e", "v8:UUID"),
    ("acf6192e-81ca-46ef-93a6-5a6968b78663", "v8:ValueTable"),
    ("e603c0f2-92fb-4d47-8f38-a44a381cf235", "v8:ValueTree"),
    ("3ee983d7-ace7-40f9-bb7e-2e916fcddd56", "v8:FixedStructure"),
    ("4500381b-db30-4a10-9db4-990038032acf", "v8:FixedArray"),
    ("220455ea-6c85-4513-996f-bbe79ed07774", "v8:FixedMap"),
    ("2fdc88ec-7c9b-43cd-8ba5-873f043bdd88", "v8:StandardPeriod"),
    (
        "0387f3a2-7df5-4804-948b-4580a51e4a15",
        "v8:StandardBeginningDate",
    ),
    ("4772b3b4-f4a3-49c0-a1a5-8cb5961511a3", "v8:ValueListType"),
    ("f5c65050-3bbb-11d5-b988-0050bae0a95d", "v8:TypeDescription"),
    ("98ea8e5a-b586-442b-b944-6e3447734aa7", "v8:FillChecking"),
    (
        "140b5ff4-37b1-4df5-b5ec-a0bfd2b94f8f",
        "v8ui:FormattedString",
    ),
    ("9cd510c7-abfc-11d4-9434-004095e12fc7", "v8ui:Color"),
    ("9cd510c8-abfc-11d4-9434-004095e12fc7", "v8ui:Font"),
    ("e6f51714-91cb-4dce-94fe-90ae3e3e1ad1", "v8ui:Picture"),
    ("52616226-8ccf-4d1d-a3da-827eeb4f9cf9", "v8ui:VerticalAlign"),
    (
        "43f9c095-40e8-441a-8fad-20a45798c71b",
        "v8ui:HorizontalAlign",
    ),
    (
        "e603103e-a318-4edc-a014-b1c6cf94d49f",
        "mxl:SpreadsheetDocument",
    ),
    (
        "151f8778-e2d0-496a-9f02-d9ffd93b57ec",
        "fd:FormattedDocument",
    ),
    ("48510817-200c-48c2-9973-06cf90840514", "pdfdoc:PDFDocument"),
    ("43dc7f37-5b1d-42a7-8f28-f545080d0255", "pl:Planner"),
    (
        "cab0d12b-3c88-4993-8edc-8c3827cadc7d",
        "dcsset:SettingsComposer",
    ),
    ("f6841c6b-6c71-4c82-ae9e-d08b49db326c", "dcsset:Filter"),
    (
        "dcbf2698-3c1f-4a22-997f-48070ae9bd64",
        "dcsset:DataCompositionComparisonType",
    ),
    (
        "a090004e-b706-453f-aa10-090a77b53757",
        "dcsset:DataCompositionFieldPlacement",
    ),
    (
        "af4a19b5-da3d-406f-be0c-81143e400452",
        "dcscor:DataCompositionSortDirection",
    ),
    (
        "0e0850cf-0634-414e-85ba-9a88a8bd44c4",
        "dcscor:DataCompositionGroupType",
    ),
    (
        "c6a52555-d20f-452c-bfc2-1b53e9a56063",
        "dcscor:DataCompositionPeriodAdditionType",
    ),
    ("913e8016-6e90-47a0-b2a0-4513f4edad61", "dcscor:Field"),
    (
        "741ae838-6e42-4ac0-b6a4-17e5604b0669",
        "ent:AccountingRecordType",
    ),
    ("b1b064f3-ae38-49bf-8c6d-390c65fd94af", "ent:ComparisonType"),
    ("dcfc3784-a14f-4786-ac7b-c82db5ba275f", "cfg:ConstantsSet"),
    ("0dda99d9-ae9f-43d2-b7ac-44f3fb0d4059", "cfg:ReportBuilder"),
    ("1dd6fdb9-553d-40d4-b2d1-c7fc31f497bb", "cfg:ReportObject"),
    ("65abad24-838b-4987-8b35-ed9e2bd4d9c8", "cfg:DynamicList"),
    ("280f5f0e-9c8a-49cc-bf6d-4d296cc17a63", "cfg:AnyIBRef"),
    ("e61ef7b8-f3e1-4f4b-8ac7-676e90524997", "cfg:CatalogRef"),
    ("38bfd075-3e63-4aaa-a93e-94521380d579", "cfg:DocumentRef"),
    ("474c3bf6-08b5-4ddc-a2ad-989cedf11583", "cfg:EnumRef"),
    (
        "0a52f9de-73ea-4507-81e8-66217bead73a",
        "cfg:ExchangePlanRef",
    ),
    (
        "99892482-ed55-4fb5-a7f7-20888820a758",
        "cfg:ChartOfCharacteristicTypesRef",
    ),
    (
        "ac606d60-0209-4159-8e4c-794bc091ce38",
        "cfg:ChartOfAccountsRef",
    ),
    (
        "593cd424-0877-470d-91f9-b90a982059b4",
        "cfg:ChartOfCalculationTypesRef",
    ),
    (
        "214fa4d8-6ba4-4748-a5e1-6332b5887780",
        "cfg:BusinessProcessRef",
    ),
    (
        "11e5f865-1501-40c6-b4d4-022095a296a5",
        "cfg:BusinessProcessRoutePointRef",
    ),
    ("6291e9b3-8df5-44e1-b6b2-d9fe008016c0", "cfg:TaskRef"),
    ("cf4abea6-37b2-11d4-940f-008048da11f9", "cfg:CatalogObject"),
    ("061d872a-5787-460e-95ac-ed74ea3a3e84", "cfg:DocumentObject"),
    (
        "857c4a91-e5f4-4fac-86ec-787626f1c108",
        "cfg:ExchangePlanObject",
    ),
    (
        "82a1b659-b220-4d94-a9bd-14d757b95a48",
        "cfg:ChartOfCharacteristicTypesObject",
    ),
    (
        "238e7e88-3c5f-48b2-8a3b-81ebbecb20ed",
        "cfg:ChartOfAccountsObject",
    ),
    (
        "30b100d6-b29f-47ac-aec7-cb8ca8a54767",
        "cfg:ChartOfCalculationTypesObject",
    ),
    (
        "fcd3404e-1523-48ce-9bc0-ecdb822684a1",
        "cfg:BusinessProcessObject",
    ),
    ("3e63355c-1378-4953-be9b-1deb5fb6bec5", "cfg:TaskObject"),
    (
        "0195e80c-b157-11d4-9435-004095e12fc7",
        "cfg:ConstantValueManager",
    ),
    (
        "13134201-f60b-11d5-a3c7-0050bae0a776",
        "cfg:InformationRegisterRecordSet",
    ),
    (
        "2deed9b8-0056-4ffe-a473-c20a6c32a0bc",
        "cfg:AccountingRegisterRecordSet",
    ),
    (
        "b64d9a40-1642-11d6-a3c7-0050bae0a776",
        "cfg:AccumulationRegisterRecordSet",
    ),
    (
        "f2de87a8-64e5-45eb-a22d-b3aedab050e7",
        "cfg:CalculationRegisterRecordSet",
    ),
    (
        "274bf899-db0e-4df6-8ab5-67bf6371ec0b",
        "cfg:SequenceRecordSet",
    ),
    (
        "bc587f20-35d9-11d6-a3c7-0050bae0a776",
        "cfg:RecalculationRecordSet",
    ),
    ("82faabf3-7f9b-4b2e-b499-98876415f270", "cfg:CatalogManager"),
    (
        "26dd1dee-252a-4942-b4b5-62ea44ed8030",
        "cfg:DocumentManager",
    ),
    (
        "92e7f73f-bd66-4d9e-bc43-bae2acfadfd5",
        "cfg:DocumentJournalManager",
    ),
    (
        "7612de75-8b10-466a-b235-68572c605d92",
        "cfg:ChartOfCharacteristicTypesManager",
    ),
    (
        "2066866d-9d38-47fe-a272-3cd416eb9c85",
        "cfg:ChartOfAccountsManager",
    ),
    (
        "3eab4ff4-f2d1-4c96-831c-04711b093999",
        "cfg:ChartOfCalculationTypesManager",
    ),
    (
        "1aa09f48-f6d5-4999-a7f5-02a15794c795",
        "cfg:InformationRegisterManager",
    ),
    (
        "0dee6ca3-50a1-4f94-8c34-e70eeb802d81",
        "cfg:AccumulationRegisterManager",
    ),
    (
        "3ab47eda-6a5c-4590-9b08-0e633aa2f376",
        "cfg:AccountingRegisterManager",
    ),
    (
        "2d0abc8e-dede-4184-afd7-7ae8da588d47",
        "cfg:CalculationRegisterManager",
    ),
    (
        "38f1038d-8b0b-438b-bfbe-830a60a1153a",
        "cfg:BusinessProcessManager",
    ),
    ("5e268c17-8035-458f-8041-daf9b15d05c9", "cfg:TaskManager"),
    ("3543ef08-3316-4f7e-9447-0cd0a1cbf1d5", "d0p1:Chart"),
    ("3a6e63bf-16aa-42eb-b48c-2fff9670ad2f", "d0p1:GanttChart"),
    ("ebf766b1-f32c-11d3-9851-008048da1252", "d0p1:TextDocument"),
    (
        "95de81b0-81c3-4936-9dbb-6400e5c90378",
        "d0p1:GeographicalSchema",
    ),
    (
        "4af83795-fc2a-48cd-9bea-ce665789a62c",
        "d0p1:FlowchartContextType",
    ),
    (
        "77a01c71-e9b2-4617-af07-c95a4b74548a",
        "d0p1:DataAnalysisTimeIntervalUnitType",
    ),
    (
        "7dd764b6-b22f-4712-8edc-c0d634340e60",
        "d0p1:ConditionalAppearance",
    ),
];

fn builtin_type_name(type_id: &str) -> Option<&'static str> {
    BUILTIN_TYPES
        .iter()
        .find_map(|(id, name)| (*id == type_id).then_some(*name))
}

/// A named type is a type set when it stands for many types: a defined
/// type, a characteristic, any reference, or every object of one family.
fn is_type_set(name: &str) -> bool {
    let Some(local) = name.strip_prefix("cfg:") else {
        return false;
    };
    // Every object of one family (`cfg:CatalogRef`, `cfg:DocumentObject`,
    // `cfg:InformationRegisterRecordSet`, `cfg:ConstantValueManager`) is a
    // set; the unnamed managers (`cfg:CatalogManager`) and the four unnamed
    // platform types are types.
    local.starts_with("DefinedType.")
        || local.starts_with("Characteristic.")
        || local == "AnyIBRef"
        || local == "ConstantValueManager"
        || (!local.contains('.')
            && (local.ends_with("Ref") || local.ends_with("Object") || local.ends_with("RecordSet"))
            && local != "ReportObject")
}

/// The order the XML writes family type sets in. References follow their
/// type ids; objects and record sets follow the platform's own order, which
/// is not their type ids' (every event subscription source of the four
/// reference trees agrees; `ConstantValueManager` and `ExchangePlanObject`
/// never meet, nor does `CalculationRegisterRecordSet` meet another set).
/// Defined types and characteristics keep their stored order, ahead.
const FAMILY_TYPE_SET_ORDER: &[&str] = &[
    "cfg:AnyIBRef",
    "cfg:ExchangePlanRef",
    "cfg:BusinessProcessRoutePointRef",
    "cfg:BusinessProcessRef",
    "cfg:DocumentRef",
    "cfg:EnumRef",
    "cfg:ChartOfCalculationTypesRef",
    "cfg:TaskRef",
    "cfg:ChartOfCharacteristicTypesRef",
    "cfg:ChartOfAccountsRef",
    "cfg:CatalogRef",
    "cfg:BusinessProcessObject",
    "cfg:ChartOfCalculationTypesObject",
    "cfg:ChartOfAccountsObject",
    "cfg:ChartOfCharacteristicTypesObject",
    "cfg:ConstantValueManager",
    "cfg:ExchangePlanObject",
    "cfg:CatalogObject",
    "cfg:TaskObject",
    "cfg:DocumentObject",
    "cfg:InformationRegisterRecordSet",
    "cfg:AccountingRegisterRecordSet",
    "cfg:AccumulationRegisterRecordSet",
    "cfg:CalculationRegisterRecordSet",
    "cfg:SequenceRecordSet",
    "cfg:RecalculationRecordSet",
];

fn type_set_rank(name: &str) -> usize {
    FAMILY_TYPE_SET_ORDER
        .iter()
        .position(|candidate| *candidate == name)
        .map_or(0, |position| position + 1)
}

/// The children a type description writes: `v8:Type` items in stored
/// order, type sets behind them, then the qualifiers (number, string, date,
/// binary).
pub(crate) fn type_children(pattern: &Brace, names: &NameIndex) -> Result<Vec<Element>> {
    let items = list(pattern)?;
    if items.first().and_then(Brace::as_str) != Some("Pattern") {
        bail!("not a type pattern: {}", short(pattern));
    }
    let mut types = Vec::new();
    let mut sets = Vec::new();
    // Type ids the configuration names nothing by follow the named ones.
    let mut unnamed = Vec::new();
    let mut number_q = None;
    let mut string_q = None;
    let mut date_q = None;
    let mut binary_q = None;
    for entry in &items[1..] {
        let fields = list(entry)?;
        let tag = fields.first().and_then(Brace::as_str).unwrap_or_default();
        match tag {
            "B" => types.push(leaf("v8:Type", "xs:boolean")),
            "S" => {
                types.push(leaf("v8:Type", "xs:string"));
                let (length, allowed) = if fields.len() >= 3 {
                    (
                        atom(&fields[1])?.to_string(),
                        if atom(&fields[2])? == "0" {
                            "Fixed"
                        } else {
                            "Variable"
                        },
                    )
                } else {
                    ("0".to_string(), "Variable")
                };
                string_q = Some(
                    el("v8:StringQualifiers")
                        .child(leaf("v8:Length", length))
                        .child(leaf("v8:AllowedLength", allowed)),
                );
            }
            "N" => {
                types.push(leaf("v8:Type", "xs:decimal"));
                let (digits, fraction, sign) = if fields.len() >= 4 {
                    (
                        atom(&fields[1])?.to_string(),
                        atom(&fields[2])?.to_string(),
                        if atom(&fields[3])? == "1" {
                            "Nonnegative"
                        } else {
                            "Any"
                        },
                    )
                } else {
                    ("0".to_string(), "0".to_string(), "Any")
                };
                number_q = Some(
                    el("v8:NumberQualifiers")
                        .child(leaf("v8:Digits", digits))
                        .child(leaf("v8:FractionDigits", fraction))
                        .child(leaf("v8:AllowedSign", sign)),
                );
            }
            "D" => {
                types.push(leaf("v8:Type", "xs:dateTime"));
                let fractions = match fields.get(1).and_then(Brace::as_str) {
                    Some("D") => "Date",
                    Some("T") => "Time",
                    _ => "DateTime",
                };
                date_q = Some(el("v8:DateQualifiers").child(leaf("v8:DateFractions", fractions)));
            }
            "L" => types.push(leaf("v8:Type", "v8:Null")),
            "R" => {
                types.push(leaf("v8:Type", "xs:base64Binary"));
                let (length, allowed) = if fields.len() >= 3 {
                    (
                        atom(&fields[1])?.to_string(),
                        if atom(&fields[2])? == "0" {
                            "Fixed"
                        } else {
                            "Variable"
                        },
                    )
                } else {
                    ("0".to_string(), "Variable")
                };
                binary_q = Some(
                    el("v8:BinaryDataQualifiers")
                        .child(leaf("v8:Length", length))
                        .child(leaf("v8:AllowedLength", allowed)),
                );
            }
            "#" => {
                let type_id = atom(item(fields, 1)?)?;
                let name = match builtin_type_name(type_id) {
                    Some(name) => name.to_string(),
                    None => match names.type_name(type_id) {
                        Some(name) => format!("cfg:{name}"),
                        None => {
                            unnamed.push(leaf("v8:TypeId", type_id));
                            continue;
                        }
                    },
                };
                if is_type_set(&name) {
                    sets.push(leaf("v8:TypeSet", name));
                } else {
                    types.push(leaf("v8:Type", name));
                }
            }
            other => bail!("unknown type pattern item {other:?}"),
        }
    }
    sets.sort_by_key(|set| type_set_rank(&set.text));
    types.extend(sets);
    types.extend(unnamed);
    types.extend(number_q);
    types.extend(string_q);
    types.extend(date_q);
    types.extend(binary_q);
    Ok(types)
}

/// A type description property (`<Type>`, `<CommandParameterType>`).
pub(crate) fn type_element(qname: &str, pattern: &Brace, names: &NameIndex) -> Result<Element> {
    Ok(el(qname).children(type_children(pattern, names)?))
}

// ---------------------------------------------------------------------------
// Typed values.

const DESIGN_TIME_REF_TYPE: &str = "5c14e26f-099b-4d37-84a6-b433d87400da";
const FIXED_ARRAY_TYPE: &str = "4500381b-db30-4a10-9db4-990038032acf";
const METADATA_OBJECT_REF_TYPE: &str = "157fa490-4ce9-11d4-9415-008048da11f9";
const TYPE_DESCRIPTION_TYPE: &str = "f5c65050-3bbb-11d5-b988-0050bae0a95d";
const ACCOUNT_TYPE_TYPE: &str = "872f7198-7083-4e3e-b57e-a2a9802c769e";

/// Reference families: `CatalogRef` -> `Catalog`.
fn ref_family(prefix: &str) -> Option<&'static str> {
    Some(match prefix {
        "CatalogRef" => "Catalog",
        "DocumentRef" => "Document",
        "EnumRef" => "Enum",
        "ExchangePlanRef" => "ExchangePlan",
        "ChartOfCharacteristicTypesRef" => "ChartOfCharacteristicTypes",
        "ChartOfAccountsRef" => "ChartOfAccounts",
        "ChartOfCalculationTypesRef" => "ChartOfCalculationTypes",
        "BusinessProcessRef" => "BusinessProcess",
        "TaskRef" => "Task",
        _ => return None,
    })
}

/// `{0,<ref type id>,<value uuid>}` -> `Catalog.X.EmptyRef`,
/// `Enum.E.EnumValue.V`, `Catalog.X.<predefined item>`, or the stored pair
/// when the type or the value is named by nothing.
pub(crate) fn design_time_ref_text(type_id: &str, value: &str, names: &NameIndex) -> String {
    if is_nil(type_id) && is_nil(value) {
        return String::new();
    }
    if let Some(type_name) = names.type_name(type_id)
        && let Some((prefix, object)) = type_name.split_once('.')
        && let Some(family) = ref_family(prefix)
    {
        let owner = format!("{family}.{object}");
        if is_nil(value) {
            return format!("{owner}.EmptyRef");
        }
        if let Some(full) = names.name(value)
            && full.starts_with(&format!("{owner}.EnumValue."))
        {
            return full.to_string();
        }
        if let Some(item) = names.predefined(value) {
            return format!("{owner}.{item}");
        }
    }
    format!("{type_id}.{value}")
}

/// `yyyymmddhhmmss` -> `yyyy-mm-ddThh:mm:ss`.
fn date_text(digits: &str) -> Result<String> {
    if digits.len() != 14 || !digits.bytes().all(|byte| byte.is_ascii_digit()) {
        bail!("bad stored date {digits}");
    }
    Ok(format!(
        "{}-{}-{}T{}:{}:{}",
        &digits[0..4],
        &digits[4..6],
        &digits[6..8],
        &digits[8..10],
        &digits[10..12],
        &digits[12..14]
    ))
}

/// A typed value (`MinValue`, `FillValue`, a choice parameter's value, a
/// fixed array's member) as an element named `qname`.
pub(crate) fn value_element(qname: &str, node: &Brace, names: &NameIndex) -> Result<Element> {
    let fields = list(node)?;
    let tag = fields.first().and_then(Brace::as_str).unwrap_or_default();
    let typed = |xsi_type: &str, text: String| leaf(qname, text).attr("type", xsi_type);
    Ok(match tag {
        "U" => el(qname).attr("nil", "true"),
        "S" => typed("xs:string", xml_text(string(item(fields, 1)?)?)),
        "B" => typed("xs:boolean", bool_text(item(fields, 1)?)?.to_string()),
        "N" => typed("xs:decimal", atom(item(fields, 1)?)?.to_string()),
        "D" => typed("xs:dateTime", date_text(atom(item(fields, 1)?)?)?),
        "#" => {
            let type_id = atom(item(fields, 1)?)?;
            let payload = item(fields, 2)?;
            match type_id {
                DESIGN_TIME_REF_TYPE => {
                    let pair = list(payload)?;
                    typed(
                        "xr:DesignTimeRef",
                        design_time_ref_text(atom(item(pair, 1)?)?, atom(item(pair, 2)?)?, names),
                    )
                }
                METADATA_OBJECT_REF_TYPE => {
                    let reference = list(payload)?;
                    let uuid = atom(item(reference, 1)?)?;
                    let name = names
                        .name(uuid)
                        .map(str::to_string)
                        .unwrap_or_else(|| uuid.to_string());
                    typed("xr:MDObjectRef", name)
                }
                TYPE_DESCRIPTION_TYPE => el(qname)
                    .attr("type", "v8:TypeDescription")
                    .children(type_children(payload, names)?),
                ACCOUNT_TYPE_TYPE => typed(
                    "ent:AccountType",
                    match number(payload)? {
                        0 => "Active",
                        1 => "Passive",
                        2 => "ActivePassive",
                        other => bail!("unknown account type {other}"),
                    }
                    .to_string(),
                ),
                FIXED_ARRAY_TYPE => {
                    let members = list(payload)?;
                    let count = number(item(members, 0)?)? as usize;
                    let mut array = el(qname).attr("type", "v8:FixedArray");
                    for member in members.iter().skip(1).take(count) {
                        array
                            .children
                            .push(value_element("v8:Value", member, names)?);
                    }
                    array
                }
                other => bail!("unsupported typed value {other}"),
            }
        }
        other => bail!("unsupported typed value tag {other:?}"),
    })
}

// ---------------------------------------------------------------------------
// Data paths and standard attribute names.

/// A family's standard attributes by the code a data path or a
/// standard-attribute block names them with.
pub(crate) fn standard_attribute_codes(kind: &str) -> Option<&'static [(&'static str, i64)]> {
    Some(match kind {
        "Catalog" => super::super::objects::CATALOG_STANDARD,
        "Document" => super::super::objects::DOCUMENT_STANDARD,
        "ExchangePlan" => super::super::objects::EXCHANGE_PLAN_STANDARD,
        "ChartOfCharacteristicTypes" => super::super::objects::CCT_STANDARD,
        "ChartOfAccounts" => super::super::objects::COA_STANDARD,
        "ChartOfCalculationTypes" => super::super::objects::CCALC_STANDARD,
        "BusinessProcess" => super::super::objects::BUSINESS_PROCESS_STANDARD,
        "Task" => super::super::objects::TASK_STANDARD,
        "Enum" => super::super::objects::ENUM_STANDARD,
        "InformationRegister" => &[
            ("Active", -5),
            ("LineNumber", -4),
            ("Recorder", -3),
            ("Period", -2),
        ],
        "AccumulationRegister" => &[
            ("RecordType", -9),
            ("Active", -5),
            ("LineNumber", -4),
            ("Recorder", -3),
            ("Period", -2),
        ],
        "AccountingRegister" => &[
            ("PeriodAdjustment", -30),
            ("Account", -10),
            ("RecordType", -9),
            ("Active", -5),
            ("LineNumber", -4),
            ("Recorder", -3),
            ("Period", -2),
        ],
        "CalculationRegister" => &[
            ("RegistrationPeriod", -13),
            ("ReversingEntry", -11),
            ("Active", -10),
            ("EndOfBasePeriod", -9),
            ("BegOfBasePeriod", -8),
            ("EndOfActionPeriod", -7),
            ("BegOfActionPeriod", -6),
            ("ActionPeriod", -5),
            ("CalculationType", -4),
            ("LineNumber", -3),
            ("Recorder", -2),
        ],
        "DocumentJournal" => &[
            ("Type", -60003),
            ("Ref", -101),
            ("Date", -100),
            ("Posted", -7),
            ("DeletionMark", -4),
            ("Number", -2),
        ],
        _ => return None,
    })
}

/// The name of a standard attribute of `base` (an object, or a tabular
/// section `X.Y.TabularSection.T`) by its code.
pub(crate) fn standard_attribute_name(base: &str, code: i64) -> Result<String> {
    let kind = base.split('.').next().unwrap_or_default();
    if base.contains(".TabularSection.") && code == super::super::objects::line_number_marker(kind)
    {
        return Ok("LineNumber".to_string());
    }
    standard_attribute_codes(kind)
        .and_then(|table| {
            table
                .iter()
                .find_map(|(name, value)| (*value == code).then_some(*name))
        })
        .map(str::to_string)
        .ok_or_else(|| anyhow!("no standard attribute {code} of {base}"))
}

/// A field reference `{-N}` / `{0,<uuid>}` / `{0}` / `{-1}` -> its text,
/// relative to `base` for standard attributes.
pub(crate) fn field_text(segment: &Brace, base: &str, names: &NameIndex) -> Result<String> {
    let fields = list(segment)?;
    match fields {
        [code] => {
            let code = number(code)?;
            match code {
                0 => Ok("0".to_string()),
                -1 => Ok("-1".to_string()),
                _ => Ok(format!(
                    "{base}.StandardAttribute.{}",
                    standard_attribute_name(base, code)?
                )),
            }
        }
        [kind, uuid] if atom(kind)? == "0" => {
            let uuid = atom(uuid)?;
            names
                .name(uuid)
                .map(str::to_string)
                .ok_or_else(|| anyhow!("no name for field {uuid}"))
        }
        _ => bail!("unsupported field reference {}", short(segment)),
    }
}

/// A data path's segments -> its text; `{-N}` segments are standard
/// attributes of the object the path has reached (the owner at first).
///
/// A path is named only inside its owner: one that reaches into another
/// object, or names a standard attribute the owner does not have, is written
/// raw, segment by segment (`0:<uuid>/-8`).
pub(crate) fn data_path_text(
    segments: &[Brace],
    owner: Owner<'_>,
    names: &NameIndex,
) -> Result<String> {
    if let [segment] = segments
        && list(segment)?.len() == 1
    {
        let code = number(&list(segment)?[0])?;
        if code == 0 {
            return Ok("0".to_string());
        }
    }
    match named_data_path(segments, owner, names)? {
        Some(named) => Ok(named),
        None => raw_data_path(segments),
    }
}

fn named_data_path(
    segments: &[Brace],
    owner: Owner<'_>,
    names: &NameIndex,
) -> Result<Option<String>> {
    let inside = format!("{}.", owner.full_name);
    let mut current: Option<String> = None;
    for segment in segments {
        let fields = list(segment)?;
        match fields {
            [code] => {
                let code = number(code)?;
                let base = current
                    .clone()
                    .unwrap_or_else(|| owner.full_name.to_string());
                let Ok(name) = standard_attribute_name(&base, code) else {
                    return Ok(None);
                };
                current = Some(format!("{base}.StandardAttribute.{name}"));
            }
            [kind, uuid] if atom(kind)? == "0" => {
                let Some(name) = names.name(atom(uuid)?) else {
                    return Ok(None);
                };
                // A top-level object (another constant a constant's link
                // names) is named wherever it is.
                if !name.starts_with(&inside) && name.matches('.').count() != 1 {
                    return Ok(None);
                }
                current = Some(name.to_string());
            }
            _ => return Ok(None),
        }
    }
    Ok(current)
}

/// `{0,<uuid>}` -> `0:<uuid>`, `{-8}` -> `-8`, joined by `/`.
fn raw_data_path(segments: &[Brace]) -> Result<String> {
    let mut parts = Vec::with_capacity(segments.len());
    for segment in segments {
        let fields = list(segment)?;
        parts.push(match fields {
            [code] => atom(code)?.to_string(),
            [kind, uuid] => format!("{}:{}", atom(kind)?, atom(uuid)?),
            _ => bail!("unsupported data path segment {}", short(segment)),
        });
    }
    Ok(parts.join("/"))
}

// ---------------------------------------------------------------------------
// Choice parameters, links, link by type.

/// `{3,<n>,<segment>...,<link item>}` -> `<qname>` (self-closed when empty).
pub(crate) fn link_by_type_element(
    qname: &str,
    node: &Brace,
    owner: Owner<'_>,
    names: &NameIndex,
) -> Result<Element> {
    let fields = list(node)?;
    let count = number(item(fields, 1)?)? as usize;
    if count == 0 {
        return Ok(el(qname));
    }
    let segments = fields
        .get(2..2 + count)
        .ok_or_else(|| anyhow!("short link by type {}", short(node)))?;
    let link_item = atom(item(fields, 2 + count)?)?;
    Ok(el(qname)
        .child(leaf("xr:DataPath", data_path_text(segments, owner, names)?))
        .child(leaf("xr:LinkItem", link_item)))
}

/// `{5006,<n>,"name",<segments>,<segment>...,<0|1>...}` -> `<qname>`.
pub(crate) fn choice_parameter_links_element(
    qname: &str,
    node: &Brace,
    owner: Owner<'_>,
    names: &NameIndex,
) -> Result<Element> {
    let fields = list(node)?;
    let count = number(item(fields, 1)?)? as usize;
    let mut element = el(qname);
    let mut position = 2;
    for _ in 0..count {
        let name = string(item(fields, position)?)?;
        let segment_count = number(item(fields, position + 1)?)? as usize;
        let segments = fields
            .get(position + 2..position + 2 + segment_count)
            .ok_or_else(|| anyhow!("short choice parameter link {}", short(node)))?;
        let change = match atom(item(fields, position + 2 + segment_count)?)? {
            "0" => "Clear",
            "1" => "DontChange",
            other => bail!("unknown ValueChange {other}"),
        };
        element.children.push(
            el("xr:Link")
                .child(leaf("xr:Name", name))
                .child(
                    leaf("xr:DataPath", data_path_text(segments, owner, names)?)
                        .attr("type", "xs:string"),
                )
                .child(leaf("xr:ValueChange", change)),
        );
        position += 3 + segment_count;
    }
    Ok(element)
}

/// `{0,<n>,"name",<value>...}` -> `<qname><app:item name=..><app:value/>`.
pub(crate) fn choice_parameters_element(
    qname: &str,
    node: &Brace,
    names: &NameIndex,
) -> Result<Element> {
    let fields = list(node)?;
    let count = number(item(fields, 1)?)? as usize;
    let mut element = el(qname);
    for index in 0..count {
        let name = string(item(fields, 2 + 2 * index)?)?;
        let value = item(fields, 3 + 2 * index)?;
        element
            .children
            .push(el("app:item").attr("name", name).child(value_element(
                "app:value",
                value,
                names,
            )?));
    }
    Ok(element)
}

// ---------------------------------------------------------------------------
// The attribute body.

pub(crate) const CHOICE_FOLDERS_AND_ITEMS: &[(&str, i64)] =
    &[("Items", 0), ("Folders", 1), ("FoldersAndItems", 2)];
pub(crate) const QUICK_CHOICE: &[(&str, i64)] = &[("DontUse", 0), ("Use", 1), ("Auto", 2)];
pub(crate) const FILL_CHECKING: &[(&str, i64)] = &[("DontCheck", 0), ("ShowError", 1)];
pub(crate) const CREATE_ON_INPUT: &[(&str, i64)] = &[("Auto", 0), ("DontUse", 1), ("Use", 2)];
pub(crate) const CHOICE_HISTORY_ON_INPUT: &[(&str, i64)] = &[("Auto", 0), ("DontUse", 1)];

/// The uuid of an attribute body `{27,{2,<md base>,<pattern>},...}`.
pub(crate) fn attribute_header(body: &Brace) -> Result<Header> {
    let slots = list(body)?;
    if atom(item(slots, 0)?)? != "27" {
        bail!("not an attribute body: {}", short(body));
    }
    let typed = list(item(slots, 1)?)?;
    header(item(typed, 1)?)
}

/// The `<Properties>` children of an attribute body, in XML order: the
/// header, `Type`, the body's properties (`FillFromFillingValue` and
/// `FillValue` only when `with_fill`), then the owner's own `tail`.
pub(crate) fn attribute_properties(
    body: &Brace,
    with_fill: bool,
    tail: Vec<Element>,
    owner: Owner<'_>,
    context: &ExportContext,
) -> Result<Element> {
    let names = &context.names;
    let slots = list(body)?;
    if atom(item(slots, 0)?)? != "27" || slots.len() != 23 {
        bail!("not an attribute body: {}", short(body));
    }
    let typed = list(item(slots, 1)?)?;
    let head = header(item(typed, 1)?)?;
    let [name, synonym, comment] = header_elements(&head)?;
    let mut properties = el("Properties")
        .child(name)
        .child(synonym)
        .child(comment)
        .child(type_element("Type", item(typed, 2)?, names)?)
        .child(leaf("PasswordMode", bool_text(&slots[2])?))
        .child(localized_element("Format", &slots[3])?)
        .child(localized_element("EditFormat", &slots[18])?)
        .child(localized_element("ToolTip", &slots[4])?)
        .child(leaf("MarkNegatives", bool_text(&slots[5])?))
        .child(leaf("Mask", xml_text(string(&slots[6])?)))
        .child(leaf("MultiLine", bool_text(&slots[7])?))
        .child(leaf("ExtendedEdit", bool_text(&slots[17])?))
        .child(value_element("MinValue", &slots[8], names)?)
        .child(value_element("MaxValue", &slots[9], names)?);
    if with_fill {
        properties = properties
            .child(leaf("FillFromFillingValue", bool_text(&slots[20])?))
            .child(value_element("FillValue", &slots[19], names)?);
    }
    properties = properties
        .child(leaf("FillChecking", code_text(&slots[13], FILL_CHECKING)?))
        .child(leaf(
            "ChoiceFoldersAndItems",
            code_text(&slots[10], CHOICE_FOLDERS_AND_ITEMS)?,
        ))
        .child(choice_parameter_links_element(
            "ChoiceParameterLinks",
            &slots[14],
            owner,
            names,
        )?)
        .child(choice_parameters_element(
            "ChoiceParameters",
            &slots[16],
            names,
        )?)
        .child(leaf("QuickChoice", code_text(&slots[12], QUICK_CHOICE)?))
        .child(leaf(
            "CreateOnInput",
            code_text(&slots[21], CREATE_ON_INPUT)?,
        ))
        .child(leaf(
            "ChoiceForm",
            reference_name(atom(&slots[11])?, names)?,
        ))
        .child(link_by_type_element(
            "LinkByType",
            &slots[15],
            owner,
            names,
        )?)
        .child(leaf(
            "ChoiceHistoryOnInput",
            code_text(&slots[22], CHOICE_HISTORY_ON_INPUT)?,
        ));
    Ok(properties.children(tail))
}

// ---------------------------------------------------------------------------
// Standard attributes.

const STANDARD_ATTRIBUTE_CLASS: &str = "510405d3-2a0c-4fea-960a-7fee59b32f9b";

/// `{1,<n>,{<code>},<class>,<bag>...}` -> the `xr:StandardAttribute`
/// elements, named through the family's codes.
pub(crate) fn standard_attribute_elements(
    body: &Brace,
    codes: &[(&'static str, i64)],
    owner: Owner<'_>,
    context: &ExportContext,
) -> Result<Vec<Element>> {
    let fields = list(body)?;
    if atom(item(fields, 0)?)? != "1" {
        bail!("not a standard attribute block: {}", short(body));
    }
    let count = number(item(fields, 1)?)? as usize;
    let mut out = Vec::with_capacity(count);
    for index in 0..count {
        let marker = list(item(fields, 2 + 3 * index)?)?;
        let code = number(item(marker, 0)?)?;
        if atom(item(fields, 3 + 3 * index)?)? != STANDARD_ATTRIBUTE_CLASS {
            bail!("unexpected standard attribute class");
        }
        let name = codes
            .iter()
            .find_map(|(name, value)| (*value == code).then_some(*name))
            .ok_or_else(|| anyhow!("no standard attribute {code} for {}", owner.kind))?;
        let bag = item(fields, 4 + 3 * index)?;
        out.push(standard_attribute(name, bag, owner, context)?);
    }
    Ok(out)
}

/// `{0}` -> none; `{1,<body>}` -> `<StandardAttributes>`.
pub(crate) fn standard_attributes_element(
    qname: &str,
    node: &Brace,
    codes: &[(&'static str, i64)],
    owner: Owner<'_>,
    context: &ExportContext,
) -> Result<Option<Element>> {
    let fields = list(node)?;
    match fields {
        [flag] if atom(flag)? == "0" => Ok(None),
        [flag, body] if atom(flag)? == "1" => Ok(Some(
            el(qname).children(standard_attribute_elements(body, codes, owner, context)?),
        )),
        _ => bail!("bad standard attributes {}", short(node)),
    }
}

/// The bag of one standard attribute -> `<xr:StandardAttribute name=..>`
/// with its 25 properties in XML order.
fn standard_attribute(
    name: &str,
    bag: &Brace,
    owner: Owner<'_>,
    context: &ExportContext,
) -> Result<Element> {
    let names = &context.names;
    let fields = list(bag)?;
    let declared = number(item(fields, 1)?)? as usize;
    if fields.len() != 2 + 2 * declared {
        bail!("bad standard attribute bag {}", short(bag));
    }
    let mut values = std::collections::HashMap::with_capacity(declared);
    for pair in fields[2..].chunks(2) {
        values.insert(atom(&pair[0])?, &pair[1]);
    }
    let get = |key: &str| -> Result<&Brace> {
        values
            .get(key)
            .copied()
            .ok_or_else(|| anyhow!("standard attribute {name} has no {key}"))
    };
    // `{"#",<type>,<payload>}` -> payload.
    let payload = |key: &str| -> Result<&Brace> { item(list(get(key)?)?, 2) };
    // `{"#",<type>,{<type>,<code>}}` -> code.
    let nested = |key: &str| -> Result<&Brace> { item(list(payload(key)?)?, 1) };
    let flag = |key: &str| -> Result<&'static str> { bool_text(item(list(get(key)?)?, 1)?) };
    let text = |key: &str| -> Result<String> { Ok(xml_text(string(item(list(get(key)?)?, 1)?)?)) };

    let choice_form = {
        let reference = list(payload("6c4f7074-e7d4-48eb-b31b-132873666262")?)?;
        reference_name(atom(item(reference, 1)?)?, names)?
    };
    let type_reduction = match values.get("3b10624f-1e3d-495d-8093-25225efc5313") {
        // Rows before 8.3.27 do not store it: a catalog's owner denies, every
        // other standard attribute transforms.
        None if name == "Owner" => "Deny",
        None => "TransformValues",
        Some(_) => match number(nested("3b10624f-1e3d-495d-8093-25225efc5313")?)? {
            0 => "TransformValues",
            2 => "Deny",
            other => bail!("unknown TypeReductionMode {other}"),
        },
    };
    Ok(el("xr:StandardAttribute")
        .attr("name", name)
        .child(link_by_type_element(
            "xr:LinkByType",
            payload("1183c14f-f814-49c6-9233-a3c26b3f64cf")?,
            owner,
            names,
        )?)
        .child(leaf(
            "xr:FillChecking",
            code_text(
                payload("2723eb98-b4c1-498a-a6f3-70444757902f")?,
                FILL_CHECKING,
            )?,
        ))
        .child(leaf(
            "xr:MultiLine",
            flag("2bbba66b-fabf-4863-8ba3-54b3c64c896e")?,
        ))
        .child(leaf(
            "xr:FillFromFillingValue",
            flag("2c8143d5-4248-4c43-8bfb-307c0be2e415")?,
        ))
        .child(leaf(
            "xr:CreateOnInput",
            code_text(
                nested("33c74a4d-561f-4bc0-9eaa-8d21c893c0a9")?,
                CREATE_ON_INPUT,
            )?,
        ))
        .child(leaf("xr:TypeReductionMode", type_reduction))
        .child(value_element(
            "xr:MaxValue",
            get("3eaf5a8b-06d6-47b0-ac7d-a9698247f499")?,
            names,
        )?)
        .child(localized_element(
            "xr:ToolTip",
            payload("4690ff70-e3fa-4914-9127-6a9acc5fc949")?,
        )?)
        .child(leaf(
            "xr:ExtendedEdit",
            flag("4de03908-56f4-4396-a61e-17253afca9ac")?,
        ))
        .child(localized_element(
            "xr:Format",
            payload("580c29e2-8af4-4258-882a-7cf8073e61c8")?,
        )?)
        .child(leaf("xr:ChoiceForm", choice_form))
        .child(leaf(
            "xr:QuickChoice",
            code_text(
                nested("6e3a1131-37a3-4da5-8895-572d9d0c9db6")?,
                QUICK_CHOICE,
            )?,
        ))
        .child(leaf(
            "xr:ChoiceHistoryOnInput",
            code_text(
                payload("7ba608f2-e654-42a3-8885-334fe88ca910")?,
                CHOICE_HISTORY_ON_INPUT,
            )?,
        ))
        .child(localized_element(
            "xr:EditFormat",
            payload("88149a78-9448-4767-867b-0e650d165d2e")?,
        )?)
        .child(leaf(
            "xr:PasswordMode",
            flag("90ae4b5d-e0fd-49ef-a008-d67c1e75038c")?,
        ))
        .child(leaf(
            "xr:DataHistory",
            code_text(
                nested("9288a8ed-b259-46d0-a8e3-70d87956ff2d")?,
                &[("DontUse", 0), ("Use", 1)],
            )?,
        ))
        .child(leaf(
            "xr:MarkNegatives",
            flag("b02800e9-a8d1-42ab-9a12-f673e92be968")?,
        ))
        .child(value_element(
            "xr:MinValue",
            get("c65a541f-0b91-4f33-bc88-fbaaa57f9992")?,
            names,
        )?)
        .child(localized_element(
            "xr:Synonym",
            payload("cf4abea3-37b2-11d4-940f-008048da11f9")?,
        )?)
        .child(leaf(
            "xr:Comment",
            text("cf4abea4-37b2-11d4-940f-008048da11f9")?,
        ))
        .child(leaf(
            "xr:FullTextSearch",
            code_text(
                nested("d4232326-022b-421e-b6d3-88e418f74327")?,
                &[("DontUse", 0), ("Use", 1)],
            )?,
        ))
        .child(choice_parameter_links_element(
            "xr:ChoiceParameterLinks",
            payload("e3da683b-c54a-457a-a243-b9b4f9bf76dd")?,
            owner,
            names,
        )?)
        .child(value_element(
            "xr:FillValue",
            get("e6b3f5f3-bdf3-4ad0-bc60-7323b3feb208")?,
            names,
        )?)
        .child(leaf(
            "xr:Mask",
            text("f49e4ced-4033-4e6c-8755-9fbaaccd6078")?,
        ))
        .child(choice_parameters_element(
            "xr:ChoiceParameters",
            payload("fcf503b8-1c06-454a-970c-06413e64aee5")?,
            names,
        )?))
}

// ---------------------------------------------------------------------------
// The attribute body by property, in any XML order.

/// The XML properties an attribute body `{27,...}` holds, by name: the md
/// header, `Type`, and the 21 properties of its slots.
pub(crate) const ATTRIBUTE_BODY_PROPERTIES: &[&str] = &[
    "Name",
    "Synonym",
    "Comment",
    "Type",
    "PasswordMode",
    "Format",
    "EditFormat",
    "ToolTip",
    "MarkNegatives",
    "Mask",
    "MultiLine",
    "ExtendedEdit",
    "MinValue",
    "MaxValue",
    "FillFromFillingValue",
    "FillValue",
    "FillChecking",
    "ChoiceFoldersAndItems",
    "ChoiceParameterLinks",
    "ChoiceParameters",
    "QuickChoice",
    "CreateOnInput",
    "ChoiceForm",
    "LinkByType",
    "ChoiceHistoryOnInput",
];

/// A decoded attribute body: its header and its properties as XML elements
/// by name, for an owner to place in its own order (a constant writes its
/// own properties between `Type` and `PasswordMode` and has no fill value; a
/// register dimension or resource adds its own): the general form of
/// [`attribute_properties`].
pub(crate) struct AttributeElements {
    elements: Vec<(&'static str, Option<Element>)>,
}

impl AttributeElements {
    /// The element of one property of [`ATTRIBUTE_BODY_PROPERTIES`], once.
    pub fn take(&mut self, name: &str) -> Result<Element> {
        self.elements
            .iter_mut()
            .find(|(candidate, _)| *candidate == name)
            .and_then(|(_, element)| element.take())
            .ok_or_else(|| anyhow!("attribute body has no <{name}> left"))
    }

    /// The elements of `order`: body properties are taken, any other name
    /// comes from `extra` (the owner's own properties, by name).
    pub fn ordered(
        mut self,
        order: &[&str],
        mut extra: impl FnMut(&str) -> Result<Element>,
    ) -> Result<Vec<Element>> {
        let mut out = Vec::with_capacity(order.len());
        for name in order {
            if ATTRIBUTE_BODY_PROPERTIES.contains(name) {
                out.push(self.take(name)?);
            } else {
                out.push(extra(name)?);
            }
        }
        Ok(out)
    }
}

/// `{27,{2,<md base>,<pattern>},...}` -> its properties by name.
pub(crate) fn attribute_elements(
    body: &Brace,
    owner: Owner<'_>,
    context: &ExportContext,
) -> Result<AttributeElements> {
    let names = &context.names;
    let slots = list(body)?;
    if atom(item(slots, 0)?)? != "27" || slots.len() != 23 {
        bail!("not an attribute body: {}", short(body));
    }
    let typed = list(item(slots, 1)?)?;
    let head = header(item(typed, 1)?)?;
    let [name, synonym, comment] = header_elements(&head)?;
    let elements = vec![
        ("Name", name),
        ("Synonym", synonym),
        ("Comment", comment),
        ("Type", type_element("Type", item(typed, 2)?, names)?),
        ("PasswordMode", leaf("PasswordMode", bool_text(&slots[2])?)),
        ("Format", localized_element("Format", &slots[3])?),
        ("EditFormat", localized_element("EditFormat", &slots[18])?),
        ("ToolTip", localized_element("ToolTip", &slots[4])?),
        ("MarkNegatives", leaf("MarkNegatives", bool_text(&slots[5])?)),
        ("Mask", leaf("Mask", xml_text(string(&slots[6])?))),
        ("MultiLine", leaf("MultiLine", bool_text(&slots[7])?)),
        ("ExtendedEdit", leaf("ExtendedEdit", bool_text(&slots[17])?)),
        ("MinValue", value_element("MinValue", &slots[8], names)?),
        ("MaxValue", value_element("MaxValue", &slots[9], names)?),
        (
            "FillFromFillingValue",
            leaf("FillFromFillingValue", bool_text(&slots[20])?),
        ),
        ("FillValue", value_element("FillValue", &slots[19], names)?),
        (
            "FillChecking",
            leaf("FillChecking", code_text(&slots[13], FILL_CHECKING)?),
        ),
        (
            "ChoiceFoldersAndItems",
            leaf(
                "ChoiceFoldersAndItems",
                code_text(&slots[10], CHOICE_FOLDERS_AND_ITEMS)?,
            ),
        ),
        (
            "ChoiceParameterLinks",
            choice_parameter_links_element("ChoiceParameterLinks", &slots[14], owner, names)?,
        ),
        (
            "ChoiceParameters",
            choice_parameters_element("ChoiceParameters", &slots[16], names)?,
        ),
        (
            "QuickChoice",
            leaf("QuickChoice", code_text(&slots[12], QUICK_CHOICE)?),
        ),
        (
            "CreateOnInput",
            leaf("CreateOnInput", code_text(&slots[21], CREATE_ON_INPUT)?),
        ),
        (
            "ChoiceForm",
            leaf("ChoiceForm", reference_name(atom(&slots[11])?, names)?),
        ),
        (
            "LinkByType",
            link_by_type_element("LinkByType", &slots[15], owner, names)?,
        ),
        (
            "ChoiceHistoryOnInput",
            leaf(
                "ChoiceHistoryOnInput",
                code_text(&slots[22], CHOICE_HISTORY_ON_INPUT)?,
            ),
        ),
    ];
    Ok(AttributeElements {
        elements: elements
            .into_iter()
            .map(|(name, element)| (name, Some(element)))
            .collect(),
    })
}

/// `{2,<md base>,<pattern>}` (a session parameter, a sequence dimension, the
/// head of every attribute body) -> the header and the `Type` element.
pub(crate) fn typed_header_elements(node: &Brace, names: &NameIndex) -> Result<(Header, Element)> {
    let typed = list(node)?;
    if atom(item(typed, 0)?)? != "2" {
        bail!("not a typed header: {}", short(node));
    }
    Ok((
        header(item(typed, 1)?)?,
        type_element("Type", item(typed, 2)?, names)?,
    ))
}

/// `{"#",157fa490-...,{1,<uuid>}}` -> the full name it names, the uuid when
/// nothing does.
pub(crate) fn metadata_ref_text(node: &Brace, names: &NameIndex) -> Result<String> {
    let fields = list(node)?;
    if fields.first().and_then(Brace::as_str) != Some("#")
        || atom(item(fields, 1)?)? != METADATA_OBJECT_REF_TYPE
    {
        bail!("not a metadata reference: {}", short(node));
    }
    let uuid = atom(item(list(item(fields, 2)?)?, 1)?)?;
    Ok(names
        .name(uuid)
        .map(str::to_string)
        .unwrap_or_else(|| uuid.to_string()))
}

/// A procedure (`<module uuid>`, `"method"`) -> `CommonModule.X.method`;
/// empty for the nil module and an empty name.
pub(crate) fn handler_text(module: &Brace, method: &Brace, names: &NameIndex) -> Result<String> {
    let module = atom(module)?;
    let method = string(method)?;
    if is_nil(module) && method.is_empty() {
        return Ok(String::new());
    }
    Ok(format!("{}.{method}", reference_name(module, names)?))
}
