"""Assemble docs/apply/evidence/restructuring/cases.md from the lab diffs (schema part + DBNames delta)."""
import os
import re
import subprocess
import sys
import zlib

import lab
import names

OUT = os.path.join(lab.ROOT, "out")
DBA, DBM, DBC = "ibcmd_rs_04_ddl_bsp8327_a", "ibcmd_rs_04_ddl_bsp8327_m", "ibcmd_rs_04_ddl_bsp8327_c2"

CASES = [
    ("a2", DBA, "a_after", "a2_after", "String(50) attribute `ДемоНовыйРеквизит` in `Catalog._ДемоПартнеры` (native-staged)", "63 s"),
    ("b", DBA, "a2_after", "b_after", "Number(15,2) attribute in `Document._ДемоЗаказПокупателя` (native-staged)", "222 s (busy machine)"),
    ("c", DBC, "c2_0", "c_after", "new catalog `ДемоНовыйСправочник` without attributes (our `--base-free` stage)", "167 s"),
    ("dm", DBM, "m0", "dm_after", "String(10) dimension in `InformationRegister._ДемоЦеныНоменклатуры` + Number(15,2) resource in `AccumulationRegister._ДемоОстаткиТоваровВМестахХранения` (native-staged)", "115 s"),
    ("g", DBM, "e_after", "g_after", "attribute widened 50 -> 100 (case e) and index flag on (case g), one apply (native-staged)", "75 s"),
    ("f", DBM, "g_after", "f_after", "the indexed attribute deleted (native-staged)", "96 s"),
    ("h", DBM, "f_after", "h_after", "12 attributes of all basic types on `Catalog.КлючевыеОперации`, 1 on `Catalog.ВидыКонтактнойИнформации` (common attributes), 1 in a tabular section of `_ДемоПартнеры`, a new tabular section on `_ДемоКонтрагенты` (our `--base-free` stage)", "122 s"),
]


def dbnames(label, db):
    t = zlib.decompress(lab.row(label, "Params", "DBNames", db=db), -15)
    return names.parse_dbnames(t)


def schema_block(case):
    p = os.path.join(OUT, "diff_%s.txt" % case)
    if not os.path.exists(p):
        return "(no diff file)"
    t = open(p, encoding="utf-8-sig").read()
    i = t.find("== schema")
    j = t.find("== data")
    blk = t[i:j].strip().splitlines()
    # drop the noise: PK renames of rebuilt tables
    out, skip = [], 0
    for k, line in enumerate(blk):
        if re.search(r"PK___\w+__AC8ED0C4", line):
            continue
        out.append(line)
    # remove headers of tables that then have no lines
    res = []
    for k, line in enumerate(out):
        if line.startswith("  T ") and (k + 1 == len(out) or not out[k + 1].startswith("     ")):
            continue
        res.append(line)
    return "\n".join(res)


def main():
    parts = ["# Traced cases: what the native apply changed\n",
             "Generated by `scripts/restructure-lab/make_cases_md.py` from the lab diffs. Primary-key renames of rebuilt tables "
             "(`PK___...` gets a new auto-name after every rebuild) and the always-rebuilt `_ConfigChngR` are left out of the "
             "schema blocks. `DBNames` deltas: number, kind, uuid.\n"]
    for case, db, before, after, title, wall in CASES:
        parts.append("## %s - %s\n" % (case, title))
        parts.append("Apply wall time: %s.\n" % wall)
        parts.append("Schema (table/column/index changes, `snapdiff.py`):\n\n```\n%s\n```\n" % schema_block(case))
        try:
            ma, ca, ea = dbnames(before, db)
            mb, cb, eb = dbnames(after, db)
            sa = set(ea)
            added = [e for e in eb if e not in sa]
            lines = ["header max %d -> %d, entries %d -> %d" % (ma, mb, ca, cb)]
            lines += ["  +%d %s %s" % (n, k, u) for u, k, n in added]
            parts.append("`DBNames`:\n\n```\n%s\n```\n" % "\n".join(lines))
        except Exception as e:
            parts.append("`DBNames`: (not available: %s)\n" % e)
    sys.stdout.write("\n".join(parts))


if __name__ == "__main__":
    main()
